### ISSUE TITLE
SLURM in Java

### ISSUE THREAD

**Issue by varduefr** [natefoo/slurm-drmaa#56] opened 2021-08-12 14:52 UTC
Hi,
I've compiled the last slurm-drmaa and tried to use the drmaa.jar from the SGE so I can access to the methods in Java pointing to the compiled version of libdrmaa.so but I'm getting an Exception in thread "main" java.lang.UnsatisfiedLinkError: com.sun.grid.drmaa.SessionImpl.nativeInit(Ljava/lang/String;)V
So I'm using:
export DRMAA_LIBRARY_PATH=/home/vargasfr/slurm_drmaa/slurm-drmaa-1.1.2/install/lib/libdrmaa.so
export CLASSPATH=/home/vargasfr/slurm_drmaa/lib/drmaa.jar:/home/vargasfr/slurm_drmaa/slurm-drmaa-1.1.2/install/lib/libdrmaa.so:/home/vargasfr/slurm_drmaa
export LD_LIBRARY_PATH=/home/vargasfr/slurm_drmaa/slurm-drmaa-1.1.2/install/lib

From my Java file I'm importing import org.ggf.drmaa.*  (where this is coming from the drmaa.jar) and calling:
SessionFactory factory = SessionFactory.getFactory();

Any idea on how can I make this working using SLURM?

**Comment by natefoo** [comment] 2021-09-02 13:33
As discussed in #41, I do not think this is possible. Please see my comment and follow up there, as this is a duplicate of that issue.

**Closed by natefoo** 2021-09-02 13:33 UTC
